stages:
  - test

default:
  image: mcr.microsoft.com/playwright:v1.45.0-jammy
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  before_script:
    - npm ci

lint:
  stage: test
  script:
    - npm run lint

playwright_tests:
  stage: test
  variables:
    PLAYWRIGHT_HTML_REPORT: "playwright-report"
    CI: "true"
  script:
    - npx playwright --version
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - playwright-report/
      - test-results/
    reports:
      junit: results.xml
  rules:
    - if: $CI
